### ISSUE TITLE
Collaboration Request

### ISSUE THREAD

**Issue by AliMehraei** [AliMehraei/ProjectManagement#1]

**Comment by bahram200** [comment]
سلام
بهرام بهنژاد
کارشناسی ارشد مهندسی نرم افزار کامپیوتر
مهندسی نرم افزار پیشرفته-معماری نرم افزار - متدولوژی ایجاد نرم افزار
bahram.behnejad1366@gmail.com
https://github.com/bahram200/PNU_3991_AR
https://bahram200.github.io/Behnejad/
I have no experience with React

**Comment by ebrahimiz** [comment]
سلام وعرض ادب 
زهرا ابراهیمی
کارشناسی ارشد مهندسی نرم افزار کامپیوتر
مهندسی نرم افزار پیشرفته
ebrahimi.z1354a@gmail.com
https://ebrahimiz.github.io

**Comment by shahramDBI** [comment]
با سلام و احترام
شهرام دربندی
کارشناسی ارشد مهندسی نرم افزار
معماری کامپیوتر
https://github.com/shahramDBI
https://shahramdbi.github.io/
shahramdarbandi79@gmail.com

**Comment by sahel123456** [comment]
سلام
سحرزینی وندمقدم
ارشد
مهندسی نرم افزار پیشرفته،معماری نرم افزار،متدولوژی ایجادنرم افزار،سمینار
رزومه:saharzeinivand.github.io
گیت هاب:https://github.com/saharzeinivand
ایمیل:sahar.zeinivand95@gmail.com

**Comment by akmcho** [comment]
سلام 
بهرام اسدپور
درخدمتیم
https://github.com/akmcho
